---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Enable public key authentication.
  become: true
  lineinfile:
    path: "{{ users_sshd.config_path }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: ^#?PubkeyAuthentication, line: PubkeyAuthentication yes }
    - { regexp: ^#?UsePAM, line: UsePAM yes }
  notify:
    - restart sshd

- meta: flush_handlers

- include_tasks: add-users.yml

- include_tasks: remove-users.yml
