---
- shell: 'grep ansible /etc/group | cut -d: -f4 | tr "," "\n"'
  changed_when: false
  register: existing_users

- set_fact:
    users_absent_names: "{{ existing_users.stdout_lines | difference(users_present_users | map(attribute='name')) }}"

- name: Remove users.
  become: true
  user:
    name: "{{ item }}"
    remove: true
    state: absent
  with_items: "{{ users_absent_names }}"

- name: Remove sudo rights.
  become: true
  file:
    path: "/etc/sudoers.d/{{ users_absent_names }}"
    state: absent
  with_items: "{{ users_absent_names }}"
